[config]
#...

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path= '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.wofi]
input_path = './templates/colors.css'
output_path= '~/.config/wofi/colors.css'

[templates.waybar]
input_path = './templates/colors.css'
output_path= '~/.config/waybar/colors.css'

[templates.lush]
input_path = './templates/lush.lua'
output_path = '~/.config/nvim/lua/config/colors/nimi.lua'
